In [25]:
import pandas as pd


books_backup = pd.read_csv('Books_catalog')
display(books_backup)

,Title,Price,Availability,Rate
0,A Light in the Attic,Â£51.77,In stock,Three
1,Tipping the Velvet,Â£53.74,In stock,One
2,Soumission,Â£50.10,In stock,One
3,Sharp Objects,Â£47.82,In stock,Four
4,Sapiens: A Brief History of Humankind,Â£54.23,In stock,Five
...,...,...,...,...
995,Alice in Wonderland (Alice's Adventures in Won...,Â£55.53,In stock,One
996,"Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)",Â£57.06,In stock,Four
997,A Spy's Devotion (The Regency Spies of London #1),Â£16.97,In stock,Five
998,1st to Die (Women's Murder Club #1),Â£53.98,In stock,One
999,"1,000 Places to See Before You Die",Â£26.08,In stock,Five

In [ ]:
# Cleaning Data

books_df = books_backup.copy()

books_df['Volume'] = books_df['Title'].str.extract(r'(?:#|Vol\.)\s*(\d+)')
books_df['Volume'] = pd.to_numeric(books_df['Volume'], errors='coerce').fillna(1).astype(int)

books_df['Price'] = books_df['Price'].str.replace('Â£', '').str.strip().astype(float)


books_df['Title'] = (
    books_df['Title']
    .str.replace(r'#\d+', '', regex=True)
    .str.replace(r'Vol.\d+', '', regex=True)
    .str.strip()
    .str.replace(r'[-–—,._]$', '', regex=True)
    .str.strip()
    .str.replace('#', '')
)

books_df['Rate'] = (
    books_df['Rate']
    .str.replace('One', '1')
    .str.replace('Two', '2')
    .str.replace('Three', '3')
    .str.replace('Four', '4')
    .str.replace('Five', '5')
    .astype(int)
    )

#books_df.info()
display(books_df[['Title', 'Volume', 'Price', 'Rate']])

                                                 Title  Volume  Price  Rate
0                                 A Light in the Attic       1  51.77     3
1                                   Tipping the Velvet       1  53.74     1
2                                           Soumission       1  50.10     1
3                                        Sharp Objects       1  47.82     4
4                Sapiens: A Brief History of Humankind       1  54.23     5
..                                                 ...     ...    ...   ...
995  Alice in Wonderland (Alice's Adventures in Won...       1  55.53     1
996     Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human )       1  57.06     4
997    A Spy's Devotion (The Regency Spies of London )       1  16.97     5
998                  1st to Die (Women's Murder Club )       1  53.98     1
999                 1,000 Places to See Before You Die       1  26.08     5

[1000 rows x 4 columns]